"""agent keys and calls (MCP)

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 20:48:08.727668
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op



revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('grades', sa.JSON(), nullable=False),
    sa.Column('tools', sa.JSON(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('agent_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=True),
    sa.Column('key_label', sa.String(length=120), nullable=False),
    sa.Column('tool', sa.String(length=60), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('resource_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['agent_key.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_call', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_call_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_call_key_id'), ['key_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_call', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_call_key_id'))
        batch_op.drop_index(batch_op.f('ix_agent_call_at'))

    op.drop_table('agent_call')
    op.drop_table('agent_key')
    # ### end Alembic commands ###
