"""baseline v0.3

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 20:27:59.584171
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op



revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('org_label', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('id_sequence',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('kind')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('taxonomy_axis',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nature', sa.String(length=10), nullable=False),
    sa.Column('multi', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=True),
    sa.Column('rdf_property', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('ext', sa.String(length=20), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('media_type', sa.String(length=200), nullable=True),
    sa.Column('storage_key', sa.String(length=300), nullable=True),
    sa.Column('data_form', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=False),
    sa.Column('key_candidates', sa.JSON(), nullable=False),
    sa.Column('key_samples', sa.JSON(), nullable=False),
    sa.Column('stream', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('combo_title', sa.String(length=300), nullable=True),
    sa.Column('combo_description', sa.Text(), nullable=True),
    sa.Column('combo_source', sa.String(length=30), nullable=True),
    sa.Column('combo_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pub_mode', sa.Boolean(), nullable=False),
    sa.Column('lineage_waiver_reason', sa.Text(), nullable=True),
    sa.Column('lineage_waived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taxonomy_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('axis_code', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.String(length=400), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['axis_code'], ['taxonomy_axis.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('axis_code', 'code', name='uq_taxonomy_code')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_label', sa.String(length=100), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('mint_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('minted_id', sa.String(length=40), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('minted_by', sa.Integer(), nullable=True),
    sa.Column('minted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['minted_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', name='uq_mint_asset'),
    sa.UniqueConstraint('minted_id')
    )
    op.create_table('attestation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('attested_by', sa.Integer(), nullable=True),
    sa.Column('attested_label', sa.String(length=100), nullable=False),
    sa.Column('attested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['attested_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_id', 'item_id', name='uq_attestation')
    )
    op.create_table('catalog_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=40), nullable=False),
    sa.Column('iri', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publisher_label', sa.String(length=200), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(length=200), nullable=True),
    sa.Column('collection_title', sa.String(length=300), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('turtle', sa.Text(), nullable=False),
    sa.Column('jsonld', sa.Text(), nullable=False),
    sa.Column('text_summary', sa.Text(), nullable=True),
    sa.Column('schema_json', sa.Text(), nullable=True),
    sa.Column('facets', sa.JSON(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('published_by', sa.Integer(), nullable=True),
    sa.Column('published_label', sa.String(length=100), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id')
    )
    op.create_table('process_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('in_combo', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('approved_fields', sa.JSON(), nullable=False),
    sa.Column('extra_classes', sa.JSON(), nullable=False),
    sa.Column('meta_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('classification', sa.JSON(), nullable=False),
    sa.Column('class_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authoring_activity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['authoring_activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_id', 'asset_id', name='uq_pd_process_asset')
    )
    op.create_table('validation_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('shapes_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('combo_signature', sa.String(length=64), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('key_code', sa.String(length=10), nullable=True),
    sa.Column('source_table', sa.String(length=200), nullable=True),
    sa.Column('source_column', sa.String(length=200), nullable=True),
    sa.Column('target_table', sa.String(length=200), nullable=True),
    sa.Column('target_column', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['process_dataset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['process_dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serialization_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('formats', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ok_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('self_verify', sa.JSON(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_dataset_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=300), nullable=False),
    sa.Column('resource_id', sa.String(length=80), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('gate0', sa.JSON(), nullable=False),
    sa.Column('conforms', sa.Boolean(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('warning_count', sa.Integer(), nullable=False),
    sa.Column('info_count', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('report_ttl', sa.Text(), nullable=True),
    sa.Column('triple_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['validation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=300), nullable=False),
    sa.Column('fmt', sa.String(length=10), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('set_checksum', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['serialization_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('serialization_run_id', sa.Integer(), nullable=True),
    sa.Column('ruleset_version', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('max_score', sa.Double(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['process.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serialization_run_id'], ['serialization_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnosis_run')
    op.drop_table('artifact')
    op.drop_table('validation_dataset_result')
    op.drop_table('serialization_run')
    op.drop_table('relation')
    op.drop_table('validation_run')
    op.drop_table('process_dataset')
    op.drop_table('catalog_entry')
    op.drop_table('attestation')
    op.drop_table('mint_record')
    op.drop_table('activity')
    op.drop_table('taxonomy_code')
    op.drop_table('process')
    op.drop_table('asset')
    op.drop_table('taxonomy_axis')
    op.drop_table('organization')
    op.drop_table('id_sequence')
    op.drop_table('app_user')
    # ### end Alembic commands ###
